_BASE_: "../Guassian-RCNN-VGG.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 8 
  WEIGHTS: "output/FedAvg_skf2c_multiclass_test/VOC2007_sim1_2/model_final.pth"
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  TEST: ("VOC2007_cityval1",)
UNSUPNET:
  Trainer: "sourceonly"
TEST:
  EVAL_PERIOD: 400
  EVALUATOR: "VOCeval"
INPUT:
  MIN_SIZE_TRAIN: (600, )
  MIN_SIZE_TEST: 600
  RANDOM_FLIP: "horizontal"
OUTPUT_DIR: "./output/s2c_sourceonly_city_eval/"
