_BASE_: "../Guassian-RCNN-VGG.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1 
  GLOBAL_TRAINER: "sourceonly"
  LOCAL_TRAINER: "sourceonly"
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (100,)
  MAX_ITER: 100
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16
  BASE_LR: 0.016
  WARMUP_ITERS: 0
  CHECKPOINT_PERIOD: 800
  REFERENCE_BATCH_SIZE: 16
MOON:
  CONTRASTIVE_Lcon_Enable: True
  CONTRASTIVE_MU: 0.5
  CONTRASTIVE_T: 0.5
  WANDB_Enable: True
  WANDB_Project_Name: "FedAvg_moon_0103_skf2c"
DATALOADER:
  NUM_WORKERS: 2
FEDSET:
  THREAD: False
  ROUND: 3
  DATASET_LIST: ("VOC2007_foggytrain1","VOC2007_sim1","VOC2007_kitti1")   
DATASETS:
  CROSS_DATASET: True
#  TRAIN_UNLABEL: ("VOC2007_bddtrain1",)
  TEST: ("VOC2007_cityval1",)
UNSUPNET:
  Trainer: "moon"
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 0
  EMA_KEEP_RATE: 0.9996
  SOURCE_LOSS_WEIGHT: 1.0
  TARGET_UNSUP_LOSS_WEIGHT: 1.0
  GUASSIAN: True
  EFL: True
  EFL_LAMBDA: [0.5,0.5]
  TAU: [0.25,0.25]
TEST:
  EVAL_PERIOD: 400
  EVALUATOR: "VOCeval"
INPUT:
  MIN_SIZE_TRAIN: (600, )
  MIN_SIZE_TEST: 600
  RANDOM_FLIP: "horizontal"
OUTPUT_DIR: "./output/FedAvg_skf2c_sourceonly_moon_debug/"
