_BASE_: "../Guassian-RCNN-VGG.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1
  Global_PATH: "output/FedAvg_ck2b/FedAvg_0_20230116.pth"
  LOCAL_PREV_PATH: "keep_experiments/c2b_source-only/model_0027999.pth"
  GLOBAL_TRAINER: "default"
  LOCAL_TRAINER: "pt"
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (20000,)
  MAX_ITER: 20000
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16
  BASE_LR: 0.016
  CHECKPOINT_PERIOD: 4000
  REFERENCE_BATCH_SIZE: 16
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("VOC2007_citytrain1",)
  TEST: ("VOC2007_bddvalsmall",)
UNSUPNET:
  Trainer: "moon"
  TEACHER_UPDATE_ITER: 1
  EMA_KEEP_RATE: 0.9996
  SOURCE_LOSS_WEIGHT: 1.0
  TARGET_UNSUP_LOSS_WEIGHT: 1.0
  GUASSIAN: True
  EFL: True
  EFL_LAMBDA: [0.5,0.5]
  TAU: [0.25,0.25]
TEST:
  EVAL_PERIOD: 400
  EVALUATOR: "VOCeval"
INPUT:
  MIN_SIZE_TRAIN: (600, )
  MIN_SIZE_TEST: 600
  RANDOM_FLIP: "horizontal"
OUTPUT_DIR: "./output/moon_c2b/"
