_BASE_: "../Guassian-RCNN-VGG.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1 
  TEACHER_TRAINER: "default"
  STUDENT_TRAINER: "default"
  TEACHER_PATH: ('output/FedAvg_ck2b/VOC2007_kitti1_1/model_final.pth','output/FedAvg_ck2b/VOC2007_citytrain1_2/model_final.pth')
  STUDENT_PATH: 'output/FedAvg_ck2b/FedAvg_2.pth'
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (30000,)
  MAX_ITER: 30000
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16
  BASE_LR: 0.016
  WARMUP_ITERS: 400
  CHECKPOINT_PERIOD: 4000
  REFERENCE_BATCH_SIZE: 16
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  CROSS_DATASET: True
  TRAIN_UNLABEL: ("VOC2007_bddtrain1",)
  TEST: ("VOC2007_bddval1",)
UNSUPNET:
  SOURCE_IDX: 1
  Trainer: "FLtrainer"
  TEACHER_UPDATE_ITER: 1
  EMA_KEEP_RATE: 0.9996
  SOURCE_LOSS_WEIGHT: 1.0
  TARGET_UNSUP_LOSS_WEIGHT: 1.0
  GUASSIAN: True
  EFL: True
  EFL_LAMBDA: [0.5,0.5]
  TAU: [0.25,0.25]
TEST:
  EVAL_PERIOD: 400
  EVALUATOR: "VOCeval"
INPUT:
  MIN_SIZE_TRAIN: (600, )
  MIN_SIZE_TEST: 600
  RANDOM_FLIP: "horizontal"
OUTPUT_DIR: "./output/multi-teacher_ck2b_city_sourceonly_FedAvgbest/"
