_BASE_: "../Guassian-RCNN-VGG.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1 
  TEACHER_TRAINER: "pt"
  STUDENT_TRAINER: "default"
  TEACHER_PATH: ('keep_experiments/s2c/model_0015999.pth','keep_experiments/k2c/model_0019999.pth','keep_experiments/f2c_1class/model_0011999.pth')
  STUDENT_PATH: 'output/FedAvg_skf2c_sourceonly/FedAvg_0.pth'
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (30000,)
  MAX_ITER: 30000
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16
  BASE_LR: 0.016
  WARMUP_ITERS: 400
  CHECKPOINT_PERIOD: 4000
  REFERENCE_BATCH_SIZE: 16
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("VOC2007_foggytrain1",)
  TRAIN_UNLABEL: ("VOC2007_citytrain1",)
  TEST: ("VOC2007_cityval1",)
UNSUPNET:
  SOURCE_IDX: 2
  Trainer: "FLtrainer"
  TEACHER_UPDATE_ITER: 1
  EMA_KEEP_RATE: 0.9996
  SOURCE_LOSS_WEIGHT: 1.0
  TARGET_UNSUP_LOSS_WEIGHT: 1.0
  GUASSIAN: True
  EFL: True
  EFL_LAMBDA: [0.5,0.5]
  TAU: [0.25,0.25]
TEST:
  EVAL_PERIOD: 400
  EVALUATOR: "VOCeval"
INPUT:
  MIN_SIZE_TRAIN: (600, )
  MIN_SIZE_TEST: 600
  RANDOM_FLIP: "horizontal"
OUTPUT_DIR: "./output/multi-teacher_skf2c_foggy_sourceonly/"
