_BASE_: "../Guassian-RCNN-VGG.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 1 
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  TEST: ("VOC2007_bddval1",)
UNSUPNET:
  Trainer: "pt"
TEST:
  EVAL_PERIOD: 400
  EVALUATOR: "VOCeval"
INPUT:
  MIN_SIZE_TRAIN: (600, )
  MIN_SIZE_TEST: 600
  RANDOM_FLIP: "horizontal"
OUTPUT_DIR: "./output/avgbddtest/"
