MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_vgg_backbone"
  VGG:
    DEPTH: 16
  ANCHOR_GENERATOR:
    SIZES: [[128, 256, 512]]
    NAME: "DefaultAnchorGenerator"
  RPN:
    IN_FEATURES: ['vgg_block5']
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    POSITIVE_FRACTION: 0.5
  ROI_HEADS:
    NAME: "StandardROIHeads"    
    NUM_CLASSES: 1
    IN_FEATURES: ["vgg_block5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  TEST: ("VOC2007_cityval1",)
TEST:
  EVAL_PERIOD: 400
  EVALUATOR: "VOCeval"
UNSUPNET:
  Trainer: "frcnn"
INPUT:
  MIN_SIZE_TRAIN: (600, )
  MIN_SIZE_TEST: 600
  RANDOM_FLIP: "horizontal"
OUTPUT_DIR: "./output/Fedavgcitytest/"
VERSION: 2
