_BASE_: "../Guassian-RCNN-VGG.yaml"
MODEL:
  WEIGHTS: "keep_experiments/FedPT_skf2c/pt_skf2c_AVG.pth"
  ROI_HEADS:
    NUM_CLASSES: 1 
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (10,)
  MAX_ITER: 10
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16
  BASE_LR: 0.016
  WARMUP_ITERS: 0
  CHECKPOINT_PERIOD: 5
  REFERENCE_BATCH_SIZE: 16
DATALOADER:
  NUM_WORKERS: 2
FEDSET:
  THREAD: False
  ROUND: 2 
  DATASET_LIST: ("VOC2007_foggytrainsmall","VOC2007_simsmall","VOC2007_kittismall")  
DATASETS:
  CROSS_DATASET: True
  TRAIN_UNLABEL: ("VOC2007_citytrainsmall",)
  TEST: ("VOC2007_cityvalsmall",)
UNSUPNET:
  Trainer: "pt"
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 0
  EMA_KEEP_RATE: 0.9996
  SOURCE_LOSS_WEIGHT: 1.0
  TARGET_UNSUP_LOSS_WEIGHT: 1.0
  GUASSIAN: True
  EFL: True
  EFL_LAMBDA: [0.5,0.5]
  TAU: [0.25,0.25]
TEST:
  EVAL_PERIOD: 5
  EVALUATOR: "VOCeval"
INPUT:
  MIN_SIZE_TRAIN: (600, )
  MIN_SIZE_TEST: 600
  RANDOM_FLIP: "horizontal"
OUTPUT_DIR: "./output/FedAvg_skf2c_small/"
