MODEL:
  META_ARCHITECTURE: "GuassianGeneralizedRCNN"
  MASK_ON: False # 是否使用mask rcnn 的分割實例
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"  # 使用 ResNet-50 的預訓練權重
  # detectron2://ImageNetPretrained/MSRA/R-50.pkl
  # detectron2://ImageNetPretrained/MSRA/R-101.pkl
  # detectron2://ImageNetPretrained/MSRA/R-152.pkl
  # detectron2://ImageNetPretrained/MSRA/X-50-32x4d.pkl
  # detectron2://ImageNetPretrained/MSRA/X-101-32x4d.pkl
  # detectron2://ImageNetPretrained/MSRA/X-101-64x4d.pkl
  # detectron2://ImageNetPretrained/EfficientNet/B0.pkl
  # detectron2://ImageNetPretrained/EfficientNet/B1.pkl
  # detectron2://ImageNetPretrained/VGG/VGG16.pkl
  # detectron2://ImageNetPretrained/VGG/VGG19.pkl
  BACKBONE:
    NAME: "build_resnet_backbone" # 這個名稱定義在 resnet/avg01_ck2b.yaml 中，對應 MODEL.BACKBONE.NAME
  RESNETS:
    DEPTH: 50  # 使用 ResNet-50
  ANCHOR_GENERATOR:
    NAME: "DefaultAnchorGenerator"
    SIZES: [[128, 256, 512]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  PROPOSAL_GENERATOR:
    NAME: "GuassianRPN"
  RPN:
    POSITIVE_FRACTION: 0.25   # 指定 RPN 中正樣本的比例
    PRE_NMS_TOPK_TEST: 6000  # 在非極大值抑制（NMS）之前保留的候選區域數量
    POST_NMS_TOPK_TEST: 1000  # 在非極大值抑制（NMS）之後...
    IN_FEATURES: ['res4']  # 指定 RPN 使用的特徵層，resnet50 最後一層是 res4
    HEAD_NAME: 'GuassianRPNHead'  # GuassianRPNHead, KeypointRCNNROIHeads, MaskRCNNROIHeads, CascadeROIHeads, StandardROIHeads
  ROI_HEADS:
    NAME: "GuassianROIHead" # CascadeROIHeads MaskRCNNROIHeads KeypointRCNNROIHeads GuassianROIHead StandardROIHeads
    IN_FEATURES: ['res4']
    NUM_CLASSES: 8
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"  # 使用 FastRCNNConvFCHead 作為 ROI Box Head
    NUM_FC: 2  # 全連接層的數量
    FC_DIM: 1024  # 全連接層的維度
    POOLER_RESOLUTION: 7 # 指定池化層的解析度
DATASETS:
  TRAIN: ("coco_2017_train",) # 會被覆蓋
  TEST: ("coco_2017_val",)   # 會被覆蓋
SOLVER:
  IMS_PER_BATCH: 16 # 每個batch的圖片數量
  BASE_LR: 0.02 # 初始學習率
  STEPS: (60000, 80000) # 表示在訓練過程中，學習率會在第 60,000 次變成0.002 和第 80,000 次變成0.0002
  MAX_ITER: 90000 # 最大迭代次數，若小於steps 會導致學習率不下降 會被覆蓋
INPUT:
  MIN_SIZE_TRAIN: (600,) # 指定訓練時圖像的最小 pixels，圖像的最小邊長會被調整到 600 像素，長寬比不變
  MIN_SIZE_TEST: 600  # 指定測試時圖像的最小 pixels
VERSION: 2
