_BASE_: "../Guassian-RCNN-ResNet.yaml"
MODEL:
  BACKBONE:
    NAME: "build_resnet50_backbone"
    FREEZE_AT: 5
  ROI_HEADS:
    NUM_CLASSES: 8
  TEACHER_TRAINER: "default"
  STUDENT_TRAINER: "sourceonly"
  TEACHER_PATH: ('output/FedAvg_ck2b_Res_mclass_20241111/VOC2007_citytrain_2/model_final.pth',
                 'output/FedAvg_ck2b_Res_mclass_20241111/VOC2007_kitti5_2/model_final.pth')
  STUDENT_PATH:  'output/FedAvg_ck2b_Res_mclass_20241111/FedAvg_2.pth'
FEDSET:
  DYNAMIC: True
  DYNAMIC_CLASS: (8,5)
  TARGET_CLASS: 8
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (30000,)
  MAX_ITER: 30000
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16
  BASE_LR: 0.016
  WARMUP_ITERS: 400
  CHECKPOINT_PERIOD: 4000
  REFERENCE_BATCH_SIZE: 16
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  CROSS_DATASET: True
  TRAIN_UNLABEL: ("VOC2007_bddtrain8",)
  TEST: ("VOC2007_bddval8",)
UNSUPNET:
  SOURCE_IDX: 0
  Trainer: "FLtrainer"
  TEACHER_UPDATE_ITER: 1
  EMA_KEEP_RATE: 0.9996
  SOURCE_LOSS_WEIGHT: 1.0
  TARGET_UNSUP_LOSS_WEIGHT: 1.0
  GUASSIAN: True
  EFL: True
  EFL_LAMBDA: [0.5,0.5]
  TAU: [0.25,0.25]
MOON:
  CONTRASTIVE_Lcon_Enable: False
  CONTRASTIVE_MU: 0.5
  CONTRASTIVE_T: 0.5
  WANDB_Enable: True
  WANDB_Project_Name: "mt01_avg_ck2b_resnet_20241120"
TEST:
  EVAL_PERIOD: 3000
  EVALUATOR: "VOCeval"
INPUT:
  MIN_SIZE_TRAIN: (600, )
  MIN_SIZE_TEST: 600
  RANDOM_FLIP: "horizontal"
OUTPUT_DIR: "./output/mt01_avg_ck2b_resnet_20241120/"


