_BASE_: "../Guassian-RCNN-VGG.yaml"
MODEL:
  BACKBONE:
    NAME: "build_vgg_backbone_dynamic"
  ROI_HEADS:
    NUM_CLASSES: 8
  TEACHER_TRAINER: "sourceonly"
  TEACHER_PATH: ('output/PFRCNN_c2b_8class/model_final.pth','keep_experiments/k2c_source-only/model_final.pth')
FEDSET:
  THREAD: False
  DYNAMIC: False
  ROUND: 0
  DATASET_LIST: ("VOC2007_citytrain","VOC2007_kitti8")  
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (4000,)
  MAX_ITER: 4000
  IMG_PER_BATCH_LABEL: 16
  IMG_PER_BATCH_UNLABEL: 16
  BASE_LR: 0.016
  WARMUP_ITERS: 0
  CHECKPOINT_PERIOD: 800
  REFERENCE_BATCH_SIZE: 16
DATALOADER:
  NUM_WORKERS: 2
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("VOC2007_citytrain",)
  #TRAIN_UNLABEL: ("VOC2007_bddtrain1",)
  TEST: ("VOC2007_bddval8",)
UNSUPNET:
  Trainer: "sourceonly"
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 0
  EMA_KEEP_RATE: 0.9996
  SOURCE_LOSS_WEIGHT: 1.0
  TARGET_UNSUP_LOSS_WEIGHT: 1.0
  GUASSIAN: True
  EFL: True
  EFL_LAMBDA: [0.5,0.5]
  TAU: [0.25,0.25]
TEST:
  EVAL_PERIOD: 400
  EVALUATOR: "VOCeval"
INPUT:
  MIN_SIZE_TRAIN: (600, )
  MIN_SIZE_TEST: 600
  RANDOM_FLIP: "horizontal"
OUTPUT_DIR: "./output/FedMA_ck2b_cla8/"
