MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_vgg_backbone"
  VGG:
    DEPTH: 16
  ANCHOR_GENERATOR:
    SIZES: [[128, 256, 512]]
    NAME: "DefaultAnchorGenerator"
  RPN:
    IN_FEATURES: ['vgg_block5']
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
    POSITIVE_FRACTION: 0.5
  ROI_HEADS:
    NAME: "StandardROIHeads"    
    NUM_CLASSES: 1
    IN_FEATURES: ["vgg_block5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
DATASETS:
  TRAIN: ("VOC2007_sim1",)
  TEST: ("VOC2007_cityval1",)
DATALOADER:
  NUM_WORKERS: 2
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  IMS_PER_BATCH: 1
  BASE_LR: 0.0001  
  WEIGHT_DECAY: 0.001
  GAMMA: 0.1
  STEPS: (50000,)
  MAX_ITER: 70000
  CHECKPOINT_PERIOD: 4000
TEST:
  EVAL_PERIOD: 400
  EVALUATOR: "VOCeval"
INPUT:
  MIN_SIZE_TRAIN: (600, )
  MIN_SIZE_TEST: 600
OUTPUT_DIR: "./output/s2c/"
VERSION: 2
